on: workflow_dispatch
name: ExportChannelTest
jobs:
  build:
    name: ExportChannelTest
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        DISCORD_BOT_KEY: ${{ secrets.CHAT_EXPORT_BOT_KEY }}
        CHANNEL_ID: "1102676452576595990"
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        envs: DISCORD_BOT_KEY, CHANNEL_ID
        # mkdir -p /root/ti4bot/ti4bot_saves/exported_channels
        script: |
          docker version
          docker run --rm -v /root/ti4bot/ti4bot_saves/exported_channels:/out --user $(id -u):$(id -g) tyrrrz/discordchatexporter:stable export -t $DISCORD_BOT_KEY -c $CHANNEL_ID
