on: workflow_dispatch
name: ExportChannelTest
jobs:
  build:
    name: ExportChannelTest
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      env:
        DISCORD_BOT_KEY: ${{ secrets.CHAT_EXPORT_BOT_KEY }}
        CHANNEL_ID: 1102676452576595990
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        envs: DISCORD_BOT_KEY, CHANNEL_ID
        script: |
          docker version
          docker run --rm -v /opt/STORAGE/exported_channels:/out tyrrrz/discordchatexporter:stable export -t $DISCORD_BOT_KEY -c $CHANNEL_ID
