on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
name: BuildAndDeploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Node Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          passphrase: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/TI4_map_generator_bot
            git pull
            docker build -t tibot .
