on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
name: BuildAndDeploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd /root/ti4bot/TI4_map_generator_bot
          git pull
          docker kill $(docker ps -q)
          docker rm $(docker ps -a -q)
          docker rmi $(docker images -q)
          docker build --build-arg BOT_KEY=$DISCORD_BOT_KEY --build-arg USER=$DISCORD_USER --build-arg SERVER=$DISCORD_SERVER --build-arg SERVER2=$DISCORD_SERVER2 -t tibot .
          cd /root
          ./docker_run.sh
          
